#+title: Openmoviedb-web

* Getting Started

First, run the development server:

#+begin_src bash
npm run dev
# or
yarn dev
# or
pnpm dev
#+end_src

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

You can start editing the page by modifying `pages/index.tsx`. The page auto-updates as you edit the file.

[API routes](https://nextjs.org/docs/api-routes/introduction) can be accessed on [http://localhost:3000/api/hello](http://localhost:3000/api/hello). This endpoint can be edited in `pages/api/hello.ts`.

The `pages/api` directory is mapped to `/api/*`. Files in this directory are treated as [API routes](https://nextjs.org/docs/api-routes/introduction) instead of React pages.

This project uses [`next/font`](https://nextjs.org/docs/basic-features/font-optimization) to automatically optimize and load Inter, a custom Google Font.

* Tasks
** Add / Change / Delete / Fix  ~N~ [6/11]
1) [X] @ADD: Header
2) [-] @ADD: Hero section
   - [ ] @FIX: Update icon. From film emoji to openmovie-db logo
   - [X] @FIX: filters
   - [X] @ADD: Swiper
3) [-] @ADD: Recomendations section
   - [ ] @CHANGE: Move HTML code to separate component (file)
   - [ ] @FIX: Neue Machina font (idk how i can download it)
   - [X] @FIX: Change buttons placement
   - [X] @FIX: Add white space between swiper elements
   - [X] @FIX: Background
4) [X] @ADD: Genres section
   - [X] @ADD: Emojis
5) [-] @ADD: Novelties section
   - [X] @ADD: Main Card
     - [X] @ADD: Rating
     - [X] @ADD: Title
   - [ ] @ADD: Film selecting
   - [X] @CHANGE: New carousel
     - [X] @ADD: Preview selected item (big image + desc)
       - [X] @ADD: Title
       - [X] @ADD: Genres 
       - [X] @ADD: Rating
       - [X] @ADD: Description
       - [X] @ADD: Image
       - [X] @ADD: Buttons
       - [X] @ADD: Play button
   - [X] @ADD: Selected film (main film)
   - [X] @ADD: Bottom placed film list. Under selected film
   - [X] @ADD: Responsive
   
6) [X] @ADD: Carousel
7) [X] @ADD: Emoji pack
8) [X] @ADD: Move settings for ChakraUI to ~config.ts~ file
9) [X] @ADD: /Montserrat/ font
10) [ ] @CHANGE: Move "Swiper" feature from [[file:src/components/screens/Home/Hero.tsx][Hero.tsx]] to separate file
11) [ ] @BUGFIX:



   


